# Nom de l'application
spring.application.name=KCRest

# Configuration du port
server.port=9090

# Configuration de la route vers la documentation
springdoc.swagger-ui.path=/api.html

# Configuration de la base de données
spring.jpa.database-platform=edu.equipe_a.kcrest.utils.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlite:data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=equipe_a
spring.datasource.password=viveLesTigres!*
spring.jpa.show-sql=true
